services:
  bash: &base
    build: .
    image: avio-buildroot
    volumes:
      - .:/app
      - dl:/app/buildroot/dl
      - output:/app/buildroot/output
    working_dir: /app/buildroot
    command: bash

  generate_image_donotuse: &generate_image
    <<: *base
    command: bash -x -c "if [ -f /app/webkitgtk-$${BOARD_NAME}.tar.gz ]; then tar xzf /app/webkitgtk-$${BOARD_NAME}.tar.gz -C /app/buildroot; fi && make BR2_EXTERNAL=../avio_configs/ O=output/$${BOARD_NAME} $${BOARD_NAME}_defconfig && cd output/$${BOARD_NAME} && make && mkdir -p /app/images/ && cp images/avio.img /app/images/avio-$${BOARD_NAME}.img"

  rpi4:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi4

  rpi5:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi5
  
  x86_64:
    <<: *generate_image
    environment:
      - BOARD_NAME=generic-x86_64
  

  generate_toolchain_donotuse: &generate_toolchain
    <<: *base
    command: bash /app/avio_configs/scripts/build-toolchain.sh

  rpi4-toolchain:
    <<: *generate_toolchain
    environment:
      - BOARD_NAME=raspberrypi4

  rpi5-toolchain:
    <<: *generate_toolchain
    environment:
      - BOARD_NAME=raspberrypi5

  x86_64-toolchain:
    <<: *generate_toolchain
    environment:
      - BOARD_NAME=generic-x86_64

  generate_webkitgtk_donotuse: &generate_webkitgtk
    <<: *base
    command: bash /app/avio_configs/scripts/build-webkitgtk-prebuilt.sh

  rpi4-webkitgtk:
    <<: *generate_webkitgtk
    environment:
      - BOARD_NAME=raspberrypi4

  rpi5-webkitgtk:
    <<: *generate_webkitgtk
    environment:
      - BOARD_NAME=raspberrypi5

  x86_64-webkitgtk:
    <<: *generate_webkitgtk
    environment:
      - BOARD_NAME=generic-x86_64

  generate_llvm_donotuse: &generate_llvm
    <<: *base
    command: bash /app/avio_configs/scripts/build-llvm-prebuilt.sh

  x86_64-llvm:
    <<: *generate_llvm
    environment:
      - BOARD_NAME=generic-x86_64

volumes:
  dl:
  output:
